### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by kirtontt** [bthurlow/nativescript-imagecropper#69]
I have a nativescript-vue (2.5.0) app using tns version 6.5.0. When I add the line "var ImageCropper = require("nativescript-imagecropper").ImageCropper", the app crashes with the output shown below. The app crashes on both Android and iOS.

=================
An uncaught Exception occurred on "main" thread.
Calling js method onViewAttachedToWindow failed
TypeError: Right-hand side of 'instanceof' is not an object

StackTrace:
(file:///data/data/com.socaislands.mobile/files/app/vendor.js:32835:12)
	at applyAllNativeSetters(file:///data/data/com.socaislands.mobile/files/app/vendor.js:20945:31)
	at initNativeView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:20849:5)
	at ViewBase.onResumeNativeUpdates(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21988:18)
	at ViewBase._resumeNativeUpdates(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21498:12)
	at ViewBase.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21438:10)
	at View.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23991:31)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21547:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21536:5)
	at ViewBase.callLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21546:10)
	at ViewBase.loadView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21740:12)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21441:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:33802:20)
	at ViewCommon.eachChild(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23235:10)
	at ViewBase.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21440:10)
	at View.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23991:31)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21547:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21536:5)
	at ViewBase.callLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21546:10)
	at ViewBase.loadView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21740:12)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21441:13)
	at ContentView.eachChildView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:18938:7)
	at ViewCommon.eachChild(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23235:10)
	at ViewBase.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21440:10)
	at View.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23991:31)
	at ScrollViewBase.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:36115:31)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21547:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21536:5)
	at ViewBase.callLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21546:10)
	at ViewBase.loadView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21740:12)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21441:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:33802:20)
	at ViewCommon.eachChild(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23235:10)
	at ViewBase.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21440:10)
	at View.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23991:31)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21547:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21536:5)
	at ViewBase.callLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21546:10)
	at ViewBase.loadView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21740:12)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21441:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:33802:20)
	at ViewCommon.eachChild(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23235:10)
	at ViewBase.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21440:10)
	at View.onLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:23991:31)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:21547:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21536:5)
	at ViewBase.callLoaded(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21546:10)
	at ViewBase.loadView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:21740:12)
	at TabContentItemBase.loadView(file:///data/data/com.socaislands.mobile/files/app/vendor.js:42407:35)
	at (file:///data/data/com.socaislands.mobile/files/app/vendor.js:16879:14)
	at BottomNavigation._loadUnloadTabItems(file:///data/data/com.socaislands.mobile/files/app/vendor.js:16875:12)
	at BottomNavigation.setPrimaryItem(file:///data/data/com.socaislands.mobile/files/app/vendor.js:17044:14)
	at BottomNavigation.changeTab(file:///data/data/com.socaislands.mobile/files/app/vendor.js:16997:10)
	at BottomNavigation._onAttachedToWindow(file:///data/data/com.socaislands.mobile/files/app/vendor.js:16910:10)
	at AttachListener.onViewAttachedToWindow(file:///data/data/com.socaislands.mobile/files/app/vendor.js:16718:15)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.java.lang.Object_vendor_16709_26_AttachListener.onViewAttachedToWindow(Object_vendor_16709_26_AttachListener.java:18)
	at android.view.View.dispatchAttachedToWindow(View.java:21319)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6001)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at android.view.ViewGroup.addView(ViewGroup.java:5717)
	at android.view.ViewGroup.addView(ViewGroup.java:5690)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1466)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by thegarage-dev** [comment]
same error is occurring to me too

**Comment by Pre22JungMinHur** [comment]
same error occurring to me too
